import { Gummy } from './gummy';
export const GUMMYDATA: Gummy[] = [
  {
    id: 1,
    name: "GOCHIグミ",
    hardness: "かたい",
    capacity: 52,
    cost: 93,
    maker: "明治",
    review: "ゴチです！",
  },
  {
    id: 2,
    name: "アンパンマングミ",
    hardness: "ふつう",
    capacity: 0,
    cost: 70,
    maker: "不二家",
    review: "子供に大人気です！",
  },
  {
    id: 3,
    name: "男梅グミ",
    hardness: "かたい",
    capacity: 38,
    cost: 115,
    maker: "ノーベル",
    review: "酸っぱくておいしい！",
  },
  {
    id: 4,
    name: "オランジーナグミ",
    hardness: "ふつう",
    capacity: 72,
    cost: 180,
    maker: "ロッテ",
    review: "あのオランジーナのグミだから美味しい！",
  },
  {
    id: 5,
    name: "果汁グミ",
    hardness: "やわらかい",
    capacity: 51,
    cost: 93,
    maker: "明治",
    review: "定番で王道でハズレなし。",
  },
  {
    id: 6,
    name: "カンデミーナ",
    hardness: "かたい",
    capacity: 72,
    cost: 184,
    maker: "カンロ",
    review: "このかたさ、クセになります。",
  },
  {
    id: 7,
    name: "コーラアップ",
    hardness: "かたい",
    capacity: 100,
    cost: 247,
    maker: "明治",
    review: "コーラ好きにはたまりません。",
  },
  {
    id: 8,
    name: "コグミ",
    hardness: "ふつう",
    capacity: 85,
    cost: 138,
    maker: "UHA味覚糖",
    review: "安くてたくさん入っています。",
  },
  {
    id: 9,
    name: "コロロ",
    hardness: "やわらかい",
    capacity: 40,
    cost: 130,
    maker: "やわらかい",
    review: "このグミを置いていない薬局はないと言っても過言ではない。",
  },
  {
    id: 10,
    name: "さけるグミ",
    hardness: "やわらかい",
    capacity: 0,
    cost: 108,
    maker: "UHA味覚糖",
    review: "いつもとは違った食べ方をしたいあなたへ。",
  },
  {
    id: 11,
    name: "サワーズグミ",
    hardness: "かたい",
    capacity: 80,
    cost: 100,
    maker: "ノーベル",
    review: "かたくて美味しいです",
  },
  {
    id: 12,
    name: "シゲキックス",
    hardness: "かたい",
    capacity: 20,
    cost: 118,
    maker: "UHA味覚糖",
    review: "強烈な酸っぱさがたまりません。",
  },
  {
    id: 13,
    name: "シャカシャカグミ",
    hardness: "かたい",
    capacity: 51,
    cost: 100,
    maker: "カバヤ",
    review: "シャカシャカしてます。",
  },
  {
    id: 14,
    name: "そのまんまレモン",
    hardness: "ふつう",
    capacity: 25,
    cost: 204,
    maker: "ライオン",
    review: "レモンそのまんま。",
  },
  {
    id: 15,
    name: "タフグミ",
    hardness: "かたい",
    capacity: 100,
    cost: 171,
    maker: "カバヤ",
    review: "そのかたさは他の追随を許しません。",
  },
  {
    id: 16,
    name: "ちびサワーズグミ",
    hardness: "かたい",
    capacity: 80,
    cost: 127,
    maker: "ノーベル",
    review: "ちびくても一人前の美味しさ。",
  },
  {
    id: 17,
    name: "つぶグミ",
    hardness: "ふつう",
    capacity: 85,
    cost: 148,
    maker: "春日井製菓",
    review: "コスパは全グミの中でもトップレベル。",
  },
  {
    id: 18,
    name: "ナタデココグミ",
    hardness: "やわらかい",
    capacity: 44,
    cost: 120,
    maker: "ライオン",
    review: "ナタデココが好きなら食べるべきです。",
  },
  {
    id: 19,
    name: "忍者めし",
    hardness: "かたい",
    capacity: 20,
    cost: 108,
    maker: "UHA味覚糖",
    review: "仕事が忙しいあなたへ。",
  },
  {
    id: 20,
    name: "ハリボーグミ",
    hardness: "ふつう",
    capacity: 100,
    cost: 230,
    maker: "ハリボー",
    review: "世界のグミ代表です。",
  },
  {
    id: 21,
    name: "ピュアラルグミ",
    hardness: "やわらかい",
    capacity: 45,
    cost: 100,
    maker: "カバヤ",
    review: "やわらかい食感が素敵です。",
  },
  {
    id: 22,
    name: "ピュレグミ",
    hardness: "ふつうfutuu",
    capacity: 56,
    cost: 157,
    maker: "カンロ",
    review: "ざらつきとグミらしさが多くのファンを魅了します。",
  },
  {
    id: 23,
    name: "フィットチーネグミ",
    hardness: "ふつう",
    capacity: 50,
    cost: 108,
    maker: "ブルボン",
    review: "細長い形が歯にフィットします（？）。",
  },
  {
    id: 24,
    name: "ぷっちょグミ",
    hardness: "かたい",
    capacity: 38,
    cost: 120,
    maker: "UHA味覚糖",
    review: "ぷっちょのグミだけ取り出してみました。",
  },
  {
    id: 25,
    name: "フルーツの森",
    hardness: "かたい",
    capacity: 22,
    cost: 30,
    maker: "共親",
    review: "なつかしくておいしいです。",
  },
  {
    id: 26,
    name: "ペタグーグミ",
    hardness: "かたい",
    capacity: 50,
    cost: 130,
    maker: "ノーベル",
    review: "ひらべったいだけでこんなにおいしいとは。",
  },
  {
    id: 27,
    name: "ポイフル",
    hardness: "ふつう",
    capacity: 53,
    cost: 117,
    maker: "明治",
    review: "馴染みのある味です。",
  },
  {
    id: 28,
    name: "むっちりグミ",
    hardness: "ふつう",
    capacity: 195,
    cost: 100,
    maker: "UHA味覚糖",
    review: "弾力がしっかりしています。",
  },
  {
    id: 29,
    name: "もぎもぎフルーツ",
    hardness: "ふつう",
    capacity: 22,
    cost: 60,
    maker: "明治",
    review: "子供時代を思い出します。",
  },
  {
    id: 30,
    name: "超ひもQコーラ＆ソーダ味",
    hardness: "ふつう",
    capacity: 0,
    cost: 51,
    maker: "明治",
    review: "遊んで美味しいグミです。",
  },
]