import { Gummy } from './gummy';
export const GUMMYDATA: Gummy[] = [
  {
    id: 1,
    name: "GOCHIグミ",
    hardness: "かたい",
    capacity: 52,
    cost: 93,
    maker: "明治",
    review: "おいしい！",
  },
  {
    id: 2,
    name: "アンパンマングミ",
    hardness: "ふつう",
    capacity: 0,
    cost: 70,
    maker: "不二家",
    review: "おいしい！",
  },
  {
    id: 3,
    name: "男梅グミ",
    hardness: "かたい",
    capacity: 38,
    cost: 115,
    maker: "ノーベル",
    review: "おいしい！",
  },
  {
    id: 4,
    name: "オランジーナグミ",
    hardness: "ふつう",
    capacity: 72,
    cost: 180,
    maker: "ロッテ",
    review: "おいしい！",
  },
  {
    id: 5,
    name: "果汁グミ",
    hardness: "やわらかい",
    capacity: 51,
    cost: 93,
    maker: "明治",
    review: "おいしい！",
  },
  {
    id: 6,
    name: "カンデミーナ",
    hardness: "かたい",
    capacity: 72,
    cost: 184,
    maker: "カンロ",
    review: "おいしい！",
  },
  {
    id: 7,
    name: "コーラアップ",
    hardness: "かたい",
    capacity: 100,
    cost: 247,
    maker: "明治",
    review: "おいしい！",
  },
  {
    id: 8,
    name: "コグミ",
    hardness: "ふつう",
    capacity: 85,
    cost: 138,
    maker: "UHA味覚糖",
    review: "おいしい！",
  },
  {
    id: 9,
    name: "コロロ",
    hardness: "やわらかい",
    capacity: 40,
    cost: 130,
    maker: "やわらかい",
    review: "おいしい！",
  },
  {
    id: 10,
    name: "さけるグミ",
    hardness: "やわらかい",
    capacity: 0,
    cost: 108,
    maker: "UHA味覚糖",
    review: "おいしい！",
  },
  {
    id: 11,
    name: "サワーズグミ",
    hardness: "かたい",
    capacity: 80,
    cost: 100,
    maker: "ノーベル",
    review: "おいしい！",
  },
  {
    id: 12,
    name: "シゲキックス",
    hardness: "かたい",
    capacity: 20,
    cost: 118,
    maker: "UHA味覚糖",
    review: "おいしい！",
  },
  {
    id: 13,
    name: "シャカシャカグミ",
    hardness: "かたい",
    capacity: 51,
    cost: 100,
    maker: "カバヤ",
    review: "おいしい！",
  },
  {
    id: 14,
    name: "そのまんまレモン",
    hardness: "ふつう",
    capacity: 25,
    cost: 204,
    maker: "ライオン",
    review: "おいしい！",
  },
  {
    id: 15,
    name: "タフグミ",
    hardness: "かたい",
    capacity: 100,
    cost: 171,
    maker: "カバヤ",
    review: "おいしい！",
  },
  {
    id: 16,
    name: "ちびサワーズグミ",
    hardness: "かたい",
    capacity: 80,
    cost: 127,
    maker: "ノーベル",
    review: "おいしい！",
  },
  {
    id: 17,
    name: "つぶグミ",
    hardness: "ふつう",
    capacity: 85,
    cost: 148,
    maker: "春日井製菓",
    review: "おいしい！",
  },
  {
    id: 18,
    name: "ナタデココグミ",
    hardness: "やわらかい",
    capacity: 44,
    cost: 120,
    maker: "ライオン",
    review: "おいしい！",
  },
  {
    id: 19,
    name: "忍者めし",
    hardness: "かたい",
    capacity: 20,
    cost: 108,
    maker: "UHA味覚糖",
    review: "おいしい！",
  },
  {
    id: 20,
    name: "ハリボーグミ",
    hardness: "ふつう",
    capacity: 100,
    cost: 230,
    maker: "ハリボー",
    review: "おいしい！",
  },
  {
    id: 21,
    name: "ピュアラルグミ",
    hardness: "やわらかい",
    capacity: 45,
    cost: 100,
    maker: "カバヤ",
    review: "おいしい！",
  },
  {
    id: 22,
    name: "ピュレグミ",
    hardness: "ふつうfutuu",
    capacity: 56,
    cost: 157,
    maker: "カンロ",
    review: "おいしい！",
  },
  {
    id: 23,
    name: "フィットチーネグミ",
    hardness: "ふつう",
    capacity: 50,
    cost: 108,
    maker: "ブルボン",
    review: "おいしい！",
  },
  {
    id: 24,
    name: "ぷっちょグミ",
    hardness: "かたい",
    capacity: 38,
    cost: 120,
    maker: "UHA味覚糖",
    review: "おいしい！",
  },
  {
    id: 25,
    name: "フルーツの森",
    hardness: "かたい",
    capacity: 22,
    cost: 30,
    maker: "共親",
    review: "おいしい！",
  },
  {
    id: 26,
    name: "ペタグーグミ",
    hardness: "かたい",
    capacity: 50,
    cost: 130,
    maker: "ノーベル",
    review: "おいしい！",
  },
  {
    id: 27,
    name: "ポイフル",
    hardness: "ふつう",
    capacity: 53,
    cost: 117,
    maker: "明治",
    review: "おいしい！",
  },
  {
    id: 28,
    name: "むっちりグミ",
    hardness: "ふつう",
    capacity: 195,
    cost: 100,
    maker: "UHA味覚糖",
    review: "おいしい！",
  },
  {
    id: 29,
    name: "もぎもぎフルーツ",
    hardness: "ふつう",
    capacity: 22,
    cost: 60,
    maker: "明治",
    review: "おいしい！",
  },
  {
    id: 30,
    name: "超ひもQコーラ＆ソーダ味",
    hardness: "ふつう",
    capacity: 0,
    cost: 51,
    maker: "明治",
    review: "おいしい！",
  },
]